### ISSUE TITLE
File contents miss their first line

### ISSUE THREAD

**Issue by jmmv** [hanwen/p4fuse#1]
I've been playing with `p4fuse` today on OS X. It worked out of the box, in case you are interested.

However, file contents seem to miss the first line for any file I cat. This is caused by the code in `p4.go` in the `Print` function, where the first line is purposely stripped out. I suppose `p4 print` may print a header sometimes, but the client I have does not print such a line.

**Comment by hanwen** [comment]
Ah, i forgot to push my fixes

**Comment by hanwen** [comment]
fixed by https://github.com/hanwen/p4fuse/commit/fd38cd5f13cae00811a6d393f4a614a6aac65c1f

**Comment by jmmv** [comment]
Confirmed fixed. Thanks.
